### ISSUE TITLE
Enhance bitheader api

### ISSUE THREAD

**Issue by jomaway** [jomaway/typst-bytefield#17]
During the refactor a first draft of the `bitheader` api was introduced. But this has still some rough edges which needs to be fixed. 

If this is done we are mostly ready for a v0.0.4 release.

**Comment by nopeslide** [comment]
Regarding your thoughts in [#13 comment](https://github.com/jomaway/typst-bytefield/pull/13#issuecomment-1939732966).

1. How about making `msb` a left/right alignment instead of a boolean? `msb:left` is much better to comprehend than `msb_first:true` in my opinion. we could also introduce an additional `lsb` argument for sth like `lsb:right` which would be equivalent to `msb:left`.
2. regarding the problem, that `"smart"` and `"bounds"` show offsets for all following fields. how about only showing offsets of fields up to the next bitheader field? we can introduce a special `bitheader(none)` variant that draws no bitheader and can be used to explicitly stop collecting offsets after a specific number of fields. I think this beats something like specifying which rows or fields should be used for the offsets.
3. introducing argument order: positive numbers and fills (like `"smart"`) add offsets, negative numbers and fills prefixed with a minus sign (like `"-smart"`) remove offsets that were added before. i.e. `bitheader(+1,-1,+1)` is equal to `bitheader(1)

**Comment by jomaway** [comment]
>     1. How about making `msb` a left/right alignment instead of a boolean? `msb:left` is much better to comprehend than `msb_first:true` in my opinion. we could also introduce an additional `lsb` argument for sth like `lsb:right` which would be equivalent to `msb:left`.

I agree with you an that one. `msb` is already `left`| `right` on the user facing side in the current state.

>     2. regarding the problem, that `"smart"` and `"bounds"` show offsets for all following fields. how about only showing offsets of fields up to the next bitheader field? we can introduce a special `bitheader(none)` variant that draws no bitheader and can be used to explicitly stop collecting offsets after a specific number of fields. I think this beats something like specifying which rows or fields should be used for the offsets.

Could be an option which must be tested. Other idea which i had is that a `bitheader` only is valid for the current row it is shown over. Kind of like a row header and therefore it only collect data of that row below. Currently only one bitheader is possible or better said only the first is processed all following are ignored. 


>     3. introducing argument order: positive numbers and fills (like `"smart"`) add offsets, negative numbers and fills prefixed with a minus sign (like `"-smart"`) remove offsets that were added before. i.e. `bitheader(+1,-1,+1)` is equal to `bitheader(1)

This would make the user think about the position where they insert this.  Example: `bitheader("-bounds", 0,1,2,3)`  would basically have no effect for the first argument. But `bitheader( 0,1,2,3, "-bounds")` would remove depending on the fields at least the zero, as this is always a border. Don't know if it is a use case to remove bitheaders which were added before? Probably a feature which can be added later if it is needed. Want to think a bit about this.

**Comment by nopeslide** [comment]
> Other idea which i had is that a `bitheader` only is valid for the current row it is shown over. Kind of like a row header and therefore it only collect data of that row below.

This would make it harder to generate compact diagrams


> This would make the user think about the position where they insert this.

How about not ordering but counting the occurence?
If you specify an offset multiple times, you need to list it more often as a negative to omit it.

**Comment by jomaway** [comment]
Ok just to sum up the current situation and some thoughts on future development. 

## Current state 
Currently only one header is shown on top of the bytefield and it is possible to show `numbers` and `labels`.
- Numbers are only shown in the range from 0 to the set bits per row (`bits` argument). Numbers greater than that are not possible. 
- Numbers are specified by adding `int` values to the `bitheader` functions.
- Numbers can be disabled by specifying a `numbers:none` argument.
- Labels can be shown by adding a `content` field just after an number.
- Numbers can be added without a label, but a label can't be added without a number.

- The argument `msb:left` just reverts the numbers. So the zero is shown on the right side. (More on this later)
- Adding numbers for common use cases with a `string` like `"bounds"` or `"all"`

## What is currently **not possible**.
!not saying this is needed or a necessary.

- Having multiple `bitheaders`. For example one above each row. This could be helpful for register definitions. Where each bit number should be shown above the field. 
- Setting the starting number of a bitheader to show different ranges: Example 32-63 instead of 0-31. Or starting at 1 instead of zero (1-32).
- Show some labels with a number and some labels without a number. Currently each label is shown above the number or no numbers are shown at all.

## Some more thoughts on `msb`:
Current situation is like described above. 
Example: if you have a `bytefield` with 16 bits per row and a total of 32bits (in two rows) the header shows number 15-0. But actually the first row would be 31-16 in my opinion. So instead of just by reversing the bitheader numbers the ranges for all fields should be changed and then the bitheader calculation should be independent of `msb:left` or `msb:right`. 

## Some thoughts on the further development of the user api. 

- Firstly I guess we should define what the output should be like. (Discuss what should be possible and is not possible at the moment or vice versa.)

- Secondly we should define the base functionality which makes this possible. This means for me adding `int` for numbers and `content` for labels and some named arguments which are necessary. But keep this fairly simple. 

- Afterwards we can add shortcuts for common scenarios like `"bound"` or `"all"`, which are as well possible with the base functions but make it more easy to use.

**Comment by nopeslide** [comment]
> * Setting the starting number of a bitheader to show different ranges: Example 32-63 instead of 0-31. Or starting at 1 instead of zero (1-32).

> if you have a `bytefield` with 16 bits per row and a total of 32bits (in two rows) the header shows number 15-0. But actually the first row would be 31-16 in my opinion.


Very nice catch, this seems to be the distinction between row relative and global offsets.  
- Global offsets keep incrementing with each field.
- Row relative offsets are the global offset modulo the row width.

Instead of adding a new argument/parameter, I think we should offer two different fields for this.
How about `bitheader` (global) and `rowheader` (row relative)?
The current `bitheader` would essentially be renamed to `rowheader`

In this scenario a `*-header` is responsible for all offsets of fields after it until the next `*-header` of the same type.
This implies that on a bytefield with multiple rows, ie.
```typst
#bytefield(
bits:8,
bitheader("bounds"),
byte[],
byte[]
)
```
the `bitheader("bounds")` would show two rows of offsets:
on one line 0 and 7 and on the other 8 and 15.
While
```typst
#bytefield(
bits:8,
bitheader("bounds"),
byte[],
bitheader("bounds"),
byte[]
)
```
would show a single bitheader row for 0 and 7 for the first byte, and a second bitheader for 8 and 15 for the second byte. 
A `rowheader("bounds")` would only show 0 and 7 for each byte.
An initial `bitheader("bounds")` would still show all offsets if the second header is  a `rowheader`,
since it only cares for another `bitheader`.

**Comment by nopeslide** [comment]
another thought regarding the general bitheader interface. 
we do not have to specify the arguments in the bitheader call itself,
but can introduce special fields for that.
The interface doesn't have to be perfect, because it can be more ergonomic to specify it with other fields.
i.e.:  
- `flag[short][long]`
that describes a single bit with the content `short` in the data section and is displayed as label `long` in the header.
- `offset()`
to display the current offset, may take numbers for relative positions like `offset(-1)` for the offset a position before.
- `label[text]`
to display a label at the current offset
- `bounds(..fields)`
to display the bounds of the fields it got as arguments, just to annotate them, i.e. `bounds( byte[A] )` shows the start/end offset and the byte itself in the data section.

**Comment by jomaway** [comment]
> we do not have to specify the arguments in the bitheader call itself,
but can introduce special fields for that.

That's an idea which I haven't thought about and is worth investigating more. But i would like to focus on the base functionality in the "backend" first. 

> Instead of adding a new argument/parameter, I think we should offer two different fields for this.
> How about `bitheader` (global) and `rowheader` (row relative)?

If we make this distinction it is still the question how they interact and what output is generated. 
From a user or wording point of view i would expect a global header to be only shown on top of the complete bytefield. 
Therefore i think there should only one `bitheader` possible per `bytefield`.  In my opinion there can be a `repeat:true` argument to repeat this header for every row. The default could be `repeat:auto` which shows only the headers were a number is specified. 

So `bitheader("all")` on a 8 bit wide bytefield would only show a header on the top with the numbers 0 to 7.
And  `bitheader("all", repeat:true)` would show a header on each row with `0..7` , `8..15`, `16..23` and so on. This could be usefull for register definitions like in micro controller manuals.  

And we could have a `rowheader` which overwrites the global `bitheader` for the defined row or adds one if the global one is not repeated. 

As for shortcuts like "bounds" i would expect the following behaviour: 

- if `repeat:true` it shows the offsets in the corresponding header above each row.
- if `repeat:false` it only shows the offsets for the first row. 

What i am not sure about is how to show all offsets calculated with modulo in the top header. 
Maybe a second argument called "squeze" would do. Not sure what is the most wanted use case out there. 

Anyway: I try to finish the "backend" part to make multiple headers possible in general and then we can try different out different user api's. It then should also be possible to have multiple implementations side by side, which map in the background to the same header-field type.

**Comment by jomaway** [comment]
Just a quick note on the current state. 
I just finished up a v0.0.4 release to bring out annotations to everyone. 

For the header api i have two things in mind for the next version: 
- Some way to allow multiple headers aka. rowheaders on the "backend" side. 
- Specify labels without numbers on per label option. 

For future testing i would like to have a new function `bitheader_experimental` or something similar where we can test new designs without affecting the current implementation.

**Comment by jomaway** [comment]
The current bitheader implementation now allows most use cases  like:
- adding numbers and labels, 
- show or hide marker lines.
- hide all numbers, 
- shortcuts for common  scenarios. 

So with version 0.0.5 there is a good base to cover all supported options. 
For future feature requests a specific issue should be opened.
